/**
 * Assembles the browser edition into one self-contained HTML file.
 *
 * `web/app.html` holds the markup, styles and analysis core; `web/render.js`
 * holds the UI. Both are inlined here, along with a slice of the sample data,
 * because the publishing target blocks every external request.
 *
 * Usage:  node scripts/build-webapp.mjs [out.html]
 */

import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = process.cwd();
const outPath = process.argv[2] ?? "webapp.html";

const shell = readFileSync(join(root, "web/app.html"), "utf8");
const render = readFileSync(join(root, "web/render.js"), "utf8");

/** Trims the sample chat log so the page stays a reasonable size. */
function sampleChat() {
  const lines = readFileSync(join(root, "samples/chat-export.txt"), "utf8").split(/\r?\n/);
  return lines.slice(-500).join("\n");
}

const signals = readFileSync(join(root, "samples/signals.csv"), "utf8");
const chat = sampleChat();

/**
 * Embeds a string as a JS literal.
 *
 * `</script` has to be broken up or it closes the surrounding tag early, and
 * U+2028/U+2029 are line terminators in JS source even though JSON leaves them
 * raw — both would produce a syntax error in the generated page.
 */
const literal = (value) =>
  JSON.stringify(value)
    .replace(/<\/script/gi, "<\\/script")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");

const data =
  `<script>\n` +
  `/* Synthetic sample data — generated by a seeded RNG in scripts/generate-samples.ts.\n` +
  `   Not market history. */\n` +
  `const SAMPLE_SIGNALS = ${literal(signals)};\n` +
  `const SAMPLE_CHAT = ${literal(chat)};\n` +
  `</script>`;

const html = shell.replace(
  '<script src="./render.js"></script>',
  `${data}\n<script>\n${render}\n</script>`,
);

if (html.includes("./render.js")) {
  throw new Error("render.js was not inlined — the placeholder script tag changed");
}

writeFileSync(outPath, html, "utf8");

console.log(`${outPath} — ${(html.length / 1024).toFixed(0)} KB`);
